import { Navigate, Route, Routes } from 'react-router-dom';
import AppShell from '../components/layout/AppShell';
import { LandingPage, LoginPage, RegisterPage } from '../pages/public/PublicPages';
import { CandidateDashboard, JobDetailPage, JobsPage } from '../pages/candidate/CandidateJobs';
import CandidateProfile from '../pages/candidate/CandidateProfile';
import { ApplicationsPage, NotificationsPage } from '../pages/candidate/CandidateActivity';
import { EmployerDashboard, EmployerApplications, EmployerCandidates, EmployerJobForm, EmployerJobs, EmployerProfile } from '../pages/employer/EmployerPages';
import { EmployerApplicationDetail, EmployerCandidateDetail } from '../pages/employer/EmployerDetails';
import { AdminApplications, AdminCandidates, AdminDashboard, AdminEmployers, AdminJobs } from '../pages/admin/AdminPages';
import { ProtectedRoute } from './RouteGuards';

export default function AppRouter() { return <AppShell><Routes><Route path="/" element={<LandingPage />} /><Route path="/login" element={<LoginPage />} /><Route path="/register" element={<RegisterPage />} /><Route path="/jobs" element={<JobsPage />} /><Route path="/jobs/:id" element={<JobDetailPage />} /><Route element={<ProtectedRoute roles={['candidate']} />}><Route path="/candidate/dashboard" element={<CandidateDashboard />} /><Route path="/candidate/profile" element={<CandidateProfile />} /><Route path="/candidate/applications" element={<ApplicationsPage />} /><Route path="/candidate/notifications" element={<NotificationsPage />} /></Route><Route element={<ProtectedRoute roles={['employer']} />}><Route path="/employer/dashboard" element={<EmployerDashboard />} /><Route path="/employer/profile" element={<EmployerProfile />} /><Route path="/employer/jobs" element={<EmployerJobs />} /><Route path="/employer/jobs/create" element={<EmployerJobForm />} /><Route path="/employer/jobs/:id/edit" element={<EmployerJobForm />} /><Route path="/employer/applications" element={<EmployerApplications />} /><Route path="/employer/applications/:id" element={<EmployerApplicationDetail />} /><Route path="/employer/candidates" element={<EmployerCandidates />} /><Route path="/employer/candidates/:id" element={<EmployerCandidateDetail />} /></Route><Route element={<ProtectedRoute roles={['admin']} />}><Route path="/admin/dashboard" element={<AdminDashboard />} /><Route path="/admin/candidates" element={<AdminCandidates />} /><Route path="/admin/employers" element={<AdminEmployers />} /><Route path="/admin/jobs" element={<AdminJobs />} /><Route path="/admin/applications" element={<AdminApplications />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes></AppShell>; }
