import { useEffect, useState } from 'react';
import PageLayout, { DataTable } from '../../components/layout/PageLayout';
import { Card, PageHeader, StatusBadge, Button } from '../../components/ui/Primitives';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/Feedback';
import { candidateService } from '../../services/candidateService';
import { notificationService } from '../../services/platformService';
import { getApiErrorMessage } from '../../utils/apiErrors';

export function ApplicationsPage() { const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(() => { candidateService.getApplications().then(setData).catch((e) => setError(getApiErrorMessage(e))); }, []); if (error) return <PageLayout><ErrorState message={error} /></PageLayout>; if (!data) return <LoadingState />; return <PageLayout><PageHeader eyebrow="Candidate workspace" title="My applications" description="Track every opportunity from submission to outcome." />{!data.results?.length ? <EmptyState title="No applications yet" description="Your submitted applications will appear here." /> : <DataTable><thead><tr className="text-left text-xs uppercase tracking-wide text-slate-500"><th className="px-5 py-4">Role</th><th className="px-5 py-4">Company</th><th className="px-5 py-4">Location</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Applied</th></tr></thead><tbody className="divide-y divide-slate-100 text-sm">{data.results.map((item) => <tr key={item.id}><td className="px-5 py-4 font-semibold">{item.job_title}</td><td className="px-5 py-4">{item.company_name}</td><td className="px-5 py-4">{item.location}</td><td className="px-5 py-4"><StatusBadge status={item.status} /></td><td className="px-5 py-4 text-slate-500">{new Date(item.applied_at).toLocaleDateString()}</td></tr>)}</tbody></DataTable>}</PageLayout>; }

export function NotificationsPage() { const [data, setData] = useState(null); const [error, setError] = useState(''); const load = () => notificationService.list().then(setData).catch((e) => setError(getApiErrorMessage(e))); useEffect(load, []); const mark = async (id) => { await notificationService.markRead(id); load(); }; if (error) return <PageLayout><ErrorState message={error} /></PageLayout>; if (!data) return <LoadingState />; return <PageLayout><PageHeader eyebrow="Updates" title="Notifications" description="Stay up to date with applications and opportunities." />{!data.results?.length ? <EmptyState title="You are all caught up" /> : <div className="space-y-3">{data.results.map((n) => <Card key={n.id} className={`flex items-start justify-between gap-4 p-5 ${n.is_read ? 'opacity-70' : ''}`}><div><p className="font-semibold">{n.title}</p><p className="mt-1 text-sm text-slate-500">{n.message}</p><p className="mt-2 text-xs text-slate-400">{new Date(n.created_at).toLocaleString()}</p></div>{!n.is_read && <Button variant="secondary" onClick={() => mark(n.id)}>Mark read</Button>}</Card>)}</div>}</PageLayout>; }
