import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import PageLayout from '../../components/layout/PageLayout';
import { JobCard, StatCard } from '../../components/data/Cards';
import { Button, Card, Field, PageHeader, SelectField, StatusBadge } from '../../components/ui/Primitives';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/Feedback';
import { candidateService } from '../../services/candidateService';
import { jobService } from '../../services/jobService';
import { getApiErrorMessage } from '../../utils/apiErrors';

export function CandidateDashboard() { const [data, setData] = useState({ profile: null, applications: null }); const [error, setError] = useState(''); useEffect(() => { Promise.all([candidateService.getProfile(), candidateService.getApplications()]).then(([profile, applications]) => setData({ profile, applications })).catch((e) => setError(getApiErrorMessage(e))); }, []); if (error) return <PageLayout><ErrorState message={error} /></PageLayout>; if (!data.profile) return <LoadingState />; return <PageLayout><PageHeader eyebrow="Candidate workspace" title={`Welcome, ${data.profile.user?.name || 'Driver'}`} description="Keep your profile ready and discover opportunities that fit your experience." /><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Applications" value={data.applications?.count ?? 0} /><StatCard label="Experience" value={`${data.profile.experience_years || 0} yrs`} accent="orange" /><StatCard label="License category" value={data.profile.license_category || 'Add profile'} /></div><Card className="mt-8 p-6"><h2 className="text-lg font-bold">Ready for your next role?</h2><p className="mt-2 text-sm text-slate-500">Browse approved driver jobs and apply directly.</p><Link to="/jobs" className="mt-5 inline-block rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white">Explore jobs</Link></Card></PageLayout>; }

export function JobsPage() { const [filters, setFilters] = useState({ search: '', location: '', category: '', min_salary: '' }); const [data, setData] = useState(null); const [error, setError] = useState(''); const load = () => { setError(''); jobService.list(Object.fromEntries(Object.entries(filters).filter(([, value]) => value))).then(setData).catch((e) => setError(getApiErrorMessage(e))); }; useEffect(load, []); return <PageLayout><PageHeader eyebrow="Opportunities" title="Find your next driving job" description="Search approved roles by location, category, salary, or keywords." /><Card className="mb-8 p-5"><div className="grid gap-4 md:grid-cols-4"><Field label="Search" placeholder="Driver, logistics…" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /><Field label="Location" placeholder="Bengaluru" value={filters.location} onChange={(e) => setFilters({ ...filters, location: e.target.value })} /><SelectField label="Category" value={filters.category} onChange={(e) => setFilters({ ...filters, category: e.target.value })}><option value="">Any category</option><option>LMV</option><option>Heavy</option><option>Commercial</option></SelectField><Field label="Minimum salary" type="number" placeholder="20000" value={filters.min_salary} onChange={(e) => setFilters({ ...filters, min_salary: e.target.value })} /></div><Button className="mt-4" onClick={load}>Search jobs</Button></Card>{error && <ErrorState message={error} />}{!data ? <LoadingState /> : data.results?.length ? <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{data.results.map((job) => <JobCard key={job.id} job={job} />)}</div> : <EmptyState title="No jobs match those filters" description="Try a broader search or check back soon." />}</PageLayout>; }

export function JobDetailPage() { const { id } = useParams(); const navigate = useNavigate(); const [job, setJob] = useState(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); useEffect(() => { jobService.get(id).then(setJob).catch((e) => setError(getApiErrorMessage(e))); }, [id]); if (error) return <PageLayout><ErrorState message={error} /></PageLayout>; if (!job) return <LoadingState />; const apply = async () => { setSubmitting(true); setError(''); try { await jobService.apply(id, { cover_message: message }); navigate('/candidate/applications'); } catch (e) { setError(getApiErrorMessage(e)); } finally { setSubmitting(false); } }; return <PageLayout><Link to="/jobs" className="text-sm font-semibold text-blue-700">← Back to jobs</Link><Card className="mt-6 p-8"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="text-sm font-semibold text-blue-700">{job.company?.name}</p><h1 className="mt-2 text-3xl font-bold">{job.title}</h1><p className="mt-2 text-slate-500">{job.company?.location} · {job.location}</p></div><StatusBadge status={job.status} /></div><div className="mt-8 grid gap-4 rounded-xl bg-slate-50 p-5 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Salary</p><p className="font-semibold">₹{job.salary_min}–₹{job.salary_max}</p></div><div><p className="text-xs text-slate-500">Experience</p><p className="font-semibold">{job.experience_required} years</p></div><div><p className="text-xs text-slate-500">Hours</p><p className="font-semibold">{job.working_hours}</p></div></div><h2 className="mt-8 text-lg font-bold">About the role</h2><p className="mt-2 whitespace-pre-wrap text-slate-600">{job.description}</p><p className="mt-6 text-sm text-slate-500">Required documents: {job.required_documents?.join(', ') || 'Not specified'}</p><div className="mt-8 border-t border-slate-200 pt-6"><Field label="Cover message" type="textarea" placeholder="Tell the employer why you are a good fit…" value={message} onChange={(e) => setMessage(e.target.value)} />{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<Button className="mt-4" onClick={apply} disabled={submitting}>{submitting ? 'Submitting…' : 'Apply for this job'}</Button></div></Card></PageLayout>; }
