# Generated by Django 5.2.12 on 2026-09-21 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, db_index=True, max_length=120)),
                ('experience_years', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('skills', models.TextField(blank=True)),
                ('license_category', models.CharField(blank=True, db_index=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('resume', models.FileField(blank=True, upload_to='resumes/')),
                ('profile_photo', models.ImageField(blank=True, upload_to='candidate_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
