# Generated by Django 5.2.12 on 2026-09-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=180)),
                ('description', models.TextField()),
                ('driver_category', models.CharField(db_index=True, max_length=50)),
                ('experience_required', models.PositiveSmallIntegerField(default=0)),
                ('location', models.CharField(db_index=True, max_length=120)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('working_hours', models.CharField(max_length=120)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.employerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'location'], name='jobs_job_status_2c5518_idx'), models.Index(fields=['status', 'driver_category'], name='jobs_job_status_44c8b2_idx')],
            },
        ),
    ]
