# Generated by Django 5.2.12 on 2026-09-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], db_index=True, default='applied', max_length=20)),
                ('cover_message', models.TextField(blank=True)),
                ('resume_snapshot', models.FileField(blank=True, upload_to='application_resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ('-applied_at',),
                'indexes': [models.Index(fields=['job', 'status'], name='application_job_id_7836e3_idx'), models.Index(fields=['candidate', 'status'], name='application_candida_a79be7_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'candidate'), name='unique_candidate_job_application')],
            },
        ),
    ]
