import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import PageLayout from '../../components/layout/PageLayout';
import { Button, Card, PageHeader, StatusBadge } from '../../components/ui/Primitives';
import { ErrorState, LoadingState } from '../../components/ui/Feedback';
import { employerService } from '../../services/employerService';
import { getApiErrorMessage } from '../../utils/apiErrors';

export function EmployerCandidateDetail() { const { id } = useParams(); const [candidate, setCandidate] = useState(null); const [error, setError] = useState(''); useEffect(() => { employerService.getCandidate(id).then(setCandidate).catch((e) => setError(getApiErrorMessage(e))); }, [id]); if (error) return <PageLayout><ErrorState message={error} /></PageLayout>; if (!candidate) return <LoadingState />; return <PageLayout><Link to="/employer/candidates" className="text-sm font-semibold text-blue-700">← Back to candidates</Link><Card className="mt-6 max-w-2xl p-8"><PageHeader eyebrow="Candidate profile" title={candidate.name} description="Profile information permitted by the backend privacy contract." /><div className="grid gap-5 sm:grid-cols-2"><div><p className="text-xs text-slate-500">Location</p><p className="font-semibold">{candidate.location || 'Not listed'}</p></div><div><p className="text-xs text-slate-500">Experience</p><p className="font-semibold">{candidate.experience_years} years</p></div><div><p className="text-xs text-slate-500">License category</p><p className="font-semibold">{candidate.license_category || 'Not listed'}</p></div><div><p className="text-xs text-slate-500">Skills</p><p className="font-semibold">{candidate.skills || 'Not listed'}</p></div></div><p className="mt-6 text-slate-600">{candidate.bio || 'No bio provided.'}</p></Card></PageLayout>; }

export function EmployerApplicationDetail() { const { id } = useParams(); const [application, setApplication] = useState(null); const [contact, setContact] = useState(null); const [error, setError] = useState(''); useEffect(() => { employerService.getApplication(id).then(setApplication).catch((e) => setError(getApiErrorMessage(e))); }, [id]); const showContact = async () => { try { setContact(await employerService.contactCandidate(id)); setError(''); } catch (e) { setError(getApiErrorMessage(e)); } }; if (error && !application) return <PageLayout><ErrorState message={error} /></PageLayout>; if (!application) return <LoadingState />; return <PageLayout><Link to="/employer/applications" className="text-sm font-semibold text-blue-700">← Back to applications</Link><Card className="mt-6 max-w-2xl p-8"><PageHeader eyebrow="Application detail" title={application.candidate_name} description={application.job_title} /><div className="flex items-center gap-3"><StatusBadge status={application.status} /><span className="text-sm text-slate-500">Applied {new Date(application.applied_at).toLocaleDateString()}</span></div><p className="mt-6 whitespace-pre-wrap text-slate-600">{application.cover_message || 'No cover message provided.'}</p>{application.status === 'shortlisted' && <Button className="mt-6" onClick={showContact}>Reveal permitted contact</Button>}{error && <p className="mt-4 text-sm text-red-600">{error}</p>}{contact && <div className="mt-6 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><p className="font-semibold">Shortlisted contact</p><p className="mt-1">{contact.email} · {contact.phone}</p></div>}</Card></PageLayout>; }
